/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalCBSParser;
import org.xtext.example.mydsl.services.CBSGrammarAccess;

public class CBSParser extends AbstractAntlrParser {

	@Inject
	private CBSGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCBSParser createParser(XtextTokenStream stream) {
		return new InternalCBSParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ComponentBasedSystemContainer";
	}

	public CBSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CBSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
