<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ComponentBasedSystems" nsURI="http://www.example.org/ComponentBasedSystems"
    nsPrefix="ComponentBasedSystems">
  <eSubpackages name="Assembly" nsURI="http://www.example.org/ComponentBasedSystems/assembly"
      nsPrefix="assebly">
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//Core/ComposedStructure #//Core/AbstractComponent"/>
  </eSubpackages>
  <eSubpackages name="Environment" nsURI="http://www.example.org/ComponentBasedSystems/environment"
      nsPrefix="environment">
    <eClassifiers xsi:type="ecore:EClass" name="Linker">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="2"
          upperBound="-1" eType="#//Environment/Container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enviroment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
          eType="#//Environment/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linker" upperBound="-1"
          eType="#//Environment/Linker" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Allocation" nsURI="http://www.example.org/ComponentBasedSystems/allocation"
      nsPrefix="allocation">
    <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Core/ComposedStructure">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" lowerBound="1"
          eType="#//Allocation/Allocation" containment="true" eOpposite="#//Allocation/Allocation/system"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Allocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//Allocation/System"
          eOpposite="#//Allocation/System/allocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationcontext" upperBound="-1"
          eType="#//Allocation/AllocationContext" containment="true" eOpposite="#//Allocation/AllocationContext/allocation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//Environment/Container"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enviroment" lowerBound="1"
          eType="#//Environment/Enviroment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" eType="#//Allocation/Allocation"
          eOpposite="#//Allocation/Allocation/allocationcontext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" lowerBound="1"
          eType="#//Core/AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Repository" nsURI="http://www.example.org/ComponentBasedSystems/repository"
      nsPrefix="repository">
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
          upperBound="-1" eType="#//Repository/BehavioralDescription/AbstractAction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" lowerBound="1"
          upperBound="-1" eType="#//Repository/Signature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Repository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//Repository/AtomicComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//Repository/Types/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//Repository/Interface" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//Repository/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
          eType="#//Repository/Types/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//Repository/Types/ParameterType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AtomicComponent" eSuperTypes="#//Core/AbstractComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
          eType="#//Repository/Service" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesInterfaces" upperBound="-1"
          eType="#//Repository/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiersInterfaces" upperBound="-1"
          eType="#//Repository/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Core/AbstractInterface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
          eType="#//Repository/Signature" containment="true"/>
    </eClassifiers>
    <eSubpackages name="BehavioralDescription" nsURI="http://www.example.org/ComponentBasedSystems/repository/behavioralDescription"
        nsPrefix="behavioralDescription">
      <eClassifiers xsi:type="ecore:EClass" name="AbstractAction" abstract="true">
        <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
          <details key="archetype" value="Role"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//Repository/BehavioralDescription/AbstractAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalCallAction" eSuperTypes="#//Repository/BehavioralDescription/AbstractAction">
        <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
          <details key="archetype" value="Role"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" lowerBound="1"
            eType="#//Repository/Signature"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BranchAction" eSuperTypes="#//Repository/BehavioralDescription/AbstractAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
            upperBound="-1" eType="#//Repository/BehavioralDescription/BranchTransition"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LoopAction" eSuperTypes="#//Repository/BehavioralDescription/AbstractAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="bodyActions" upperBound="-1"
            eType="#//Repository/BehavioralDescription/AbstractAction" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BranchTransition">
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
            eType="#//Repository/BehavioralDescription/AbstractAction" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Types" nsURI="http://www.example.org/ComponentBasedSystems/repository/types"
        nsPrefix="types">
      <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true" eSuperTypes="#//Repository/Types/Type"/>
      <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Repository/Types/Type"/>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//Repository/Types/ParameterType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Repository/Types/SimpleTypeEnum"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeEnum">
        <eLiterals name="Int"/>
        <eLiterals name="String" value="1"/>
        <eLiterals name="Boolean" value="2"/>
        <eLiterals name="Char" value="3"/>
        <eLiterals name="Date" value="4"/>
        <eLiterals name="Double" value="5"/>
        <eLiterals name="Float" value="6"/>
        <eLiterals name="Long" value="8"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Repository/Types/ParameterType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
            eType="#//Repository/Types/ComplexMember" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComplexMember">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//Repository/Types/ParameterType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//Repository/Types/ParameterType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="innerType" lowerBound="1"
            eType="#//Repository/Types/ParameterType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Repository/Types/CollectionTypeEnum"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="CollectionTypeEnum">
        <eLiterals name="List"/>
        <eLiterals name="Map" value="1"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Core">
    <eClassifiers xsi:type="ecore:EClass" name="ProvideldRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providingComponent" lowerBound="1"
          eType="#//Core/AbstractComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" lowerBound="1"
          eType="#//Core/AbstractInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requieringComponent"
          lowerBound="1" eType="#//Core/AbstractComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" lowerBound="1"
          eType="#//Core/AbstractInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outerProvideldRole" lowerBound="1"
          eType="#//Core/ProvideldRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="innerProvideldRole" lowerBound="1"
          eType="#//Core/ProvideldRole"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="innerRequiredRole" lowerBound="1"
          eType="#//Core/RequiredRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outerRequiredRole" lowerBound="1"
          eType="#//Core/RequiredRole"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
          eType="#//Core/ProvideldRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1"
          eType="#//Core/RequiredRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiringContext" lowerBound="1"
          eType="#//Core/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providingContext" lowerBound="1"
          eType="#//Core/AssemblyContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulates" lowerBound="1"
          eType="#//Core/AbstractComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComposedStructure" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="childContexts" upperBound="-1"
          eType="#//Core/AssemblyContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredDelegationConnector"
          upperBound="-1" eType="#//Core/RequiredDelegationConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedDelegationConnectors"
          upperBound="-1" eType="#//Core/ProvidedDelegationConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnectors" upperBound="-1"
          eType="#//Core/AssemblyConnector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesRole" upperBound="-1"
          eType="#//Core/ProvideldRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresRole" upperBound="-1"
          eType="#//Core/RequiredRole"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractInterface" abstract="true"/>
  </eSubpackages>
</ecore:EPackage>
