<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ComponentBasedSystems" nsURI="http://www.example.org/ComponentBasedSystems"
    nsPrefix="ComponentBasedSystems">
  <eSubpackages name="BehavioralDescription">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAction" abstract="true">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//BehavioralDescription/AbstractAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalCallAction" eSuperTypes="#//BehavioralDescription/AbstractAction">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" lowerBound="1"
          eType="#//Repository/Signature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BranchAction" eSuperTypes="#//BehavioralDescription/AbstractAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
          upperBound="-1" eType="#//BehavioralDescription/BranchTransition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopAction" eSuperTypes="#//BehavioralDescription/AbstractAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyActions" upperBound="-1"
          eType="#//BehavioralDescription/AbstractAction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BranchTransition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="abstractaction" lowerBound="1"
          eType="#//BehavioralDescription/AbstractAction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SignatureImplementation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
          upperBound="-1" eType="#//BehavioralDescription/AbstractAction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" lowerBound="1"
          eType="#//Repository/Signature"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Assembly">
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiates" lowerBound="1"
          eType="#//Repository/Component"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="childContexts" upperBound="-1"
          eType="#//Assembly/AssemblyContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnector" upperBound="-1"
          eType="#//Assembly/AssemblyConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredDelegationConnectors"
          upperBound="-1" eType="#//Assembly/RequiredDelegationConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedDelegationConnectors"
          upperBound="-1" eType="#//Assembly/ProvidedDelegationConnector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
          eType="#//Assembly/AssemblyConnector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requires" lowerBound="1"
          eType="#//Repository/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provides" lowerBound="1"
          eType="#//Repository/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1"
          eType="#//Assembly/AssemblyConnector"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Types">
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true" eSuperTypes="#//Types/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Types/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//Types/ParameterType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//Types/SimpleTypeEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeEnum">
      <eLiterals name="String"/>
      <eLiterals name="Int" value="1"/>
      <eLiterals name="Boolean" value="2"/>
      <eLiterals name="Char" value="3"/>
      <eLiterals name="Date" value="4"/>
      <eLiterals name="Double" value="5"/>
      <eLiterals name="Float" value="6"/>
      <eLiterals name="List" value="7"/>
      <eLiterals name="Long" value="8"/>
      <eLiterals name="Map" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Types/ParameterType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//Types/ComplexMember" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexMember">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//Types/ParameterType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Enviroment">
    <eClassifiers xsi:type="ecore:EClass" name="Linker">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="2"
          upperBound="-1" eType="#//Enviroment/Container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enviroment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
          eType="#//Enviroment/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linker" upperBound="-1"
          eType="#//Enviroment/Linker" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Allocation">
    <eClassifiers xsi:type="ecore:EClass" name="System">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Allocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext" upperBound="-1"
          eType="#//Allocation/AllocationContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
          eType="#//Allocation/System"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compositecomponent" lowerBound="1"
          eType="#//Assembly/CompositeComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//Enviroment/Container"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enviroment" lowerBound="1"
          eType="#//Enviroment/Enviroment"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Repository">
    <eClassifiers xsi:type="ecore:EClass" name="Repository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//Repository/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//Repository/Component" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//Repository/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
          eType="#//Types/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//Types/ParameterType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
          eType="#//Repository/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
          eType="#//Repository/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorDescriptions"
          upperBound="-1" eType="#//BehavioralDescription/SignatureImplementation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
          eType="#//Repository/Signature" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
