/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.cbs.ui.internal.CbsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CBSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CbsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CbsActivator activator = CbsActivator.getInstance();
		return activator != null ? activator.getInjector(CbsActivator.ORG_XTEXT_EXAMPLE_MYDSL_CBS) : null;
	}

}
