/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CBSStandaloneSetup extends CBSStandaloneSetupGenerated {

	public static void doSetup() {
		new CBSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
